// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDq0wuMqs3bAv6MzxXZaxRkC7NqooHCIuw',
    appId: '1:719524969788:web:bf256aa9630767a2767239',
    messagingSenderId: '719524969788',
    projectId: 'pertolo-f3c7a',
    authDomain: 'pertolo-f3c7a.firebaseapp.com',
    storageBucket: 'pertolo-f3c7a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGSZFX7hmSggp_F32_Y0sQxeo9aFjIuus',
    appId: '1:719524969788:android:696cd42af5a3c1d9767239',
    messagingSenderId: '719524969788',
    projectId: 'pertolo-f3c7a',
    storageBucket: 'pertolo-f3c7a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPGNzkvMcONTpIyGMdUPuVwVNpMYrTH14',
    appId: '1:719524969788:ios:5ae0b3b6b0568a92767239',
    messagingSenderId: '719524969788',
    projectId: 'pertolo-f3c7a',
    storageBucket: 'pertolo-f3c7a.appspot.com',
    iosClientId: '719524969788-gqppcb2jtvl32arqa161er09ovvek03u.apps.googleusercontent.com',
    iosBundleId: 'com.example.pertolo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPGNzkvMcONTpIyGMdUPuVwVNpMYrTH14',
    appId: '1:719524969788:ios:5ae0b3b6b0568a92767239',
    messagingSenderId: '719524969788',
    projectId: 'pertolo-f3c7a',
    storageBucket: 'pertolo-f3c7a.appspot.com',
    iosClientId: '719524969788-gqppcb2jtvl32arqa161er09ovvek03u.apps.googleusercontent.com',
    iosBundleId: 'com.example.pertolo',
  );
}
